name: Action to setup SLT
description:
  This action installs SLT, conan_engine and conan
author: Luis Thomas

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  install-conan:
    description: Path to the conanfile.py file  
    type: boolean
    required: false
    default: true

outputs:
  slt-version:
    description: The SLT version downloaded
    value: ${{ steps.check-slt-version.outputs.slt-version }}

runs:
  using: 'composite'
  steps:
    - name: Check curl install
      id: check-curl-install
      run: |
        curl --version
      shell: bash

    - name: Download slt from artifactory
      id: download-slt
      run: |
        curl ${SLT_ARTIFACTORY_URL}/${SLT_PKG_VERSION}/${SLT_PKG_NAME} --output /tmp/${SLT_PKG_NAME}
        mkdir -p $HOME/.local/bin
        unzip /tmp/${SLT_PKG_NAME} -d $HOME/.local/bin
        rm /tmp/${SLT_PKG_NAME}
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash
      env:
        SLT_ARTIFACTORY_URL: https://artifactory.silabs.net/artifactory/studio-generic-development/slt/master
        SLT_PKG_NAME: slt-cli_linux_amd64.zip
        SLT_PKG_VERSION: 0.0.8-218
    
    - name: Check slt version
      id: check-slt-version
      run: |
        echo "slt-version=$(slt --version)" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: install conan_engine and conan, also export CONAN_HOME in env
      if: ${{ inputs.install-conan }}
      id: install-conan
      run: |
        slt install foo --engine conan || true
        ln -s $HOME/.silabs/slt/engines/conan/conan_engine $HOME/.local/bin/conan_engine
        ln -s $HOME/.silabs/slt/engines/conan/conan/conan $HOME/.local/bin/conan
        conan_engine --version
        conan --version
        echo "CONAN_HOME=$HOME/.silabs/slt/installs/conan" >> $GITHUB_ENV 
      shell: bash
